### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MillivoltLightningbolt** [deep-insights-ai/covid-19-classifier#4]
anybody:
- [ ] automate testset run

A:

- [x] press release
- [x] update about page
- [x] write disclaimer on upload. Especially privacy.
- [x] put model on server & link it on github
- [x] make results prettier
- [x] alternative description for "OTHER"
- [x] make contributing.md file
- [x] make FAQ on website
- [ ] include methodology.md on website
- [x] contact J with MP in cc
optional:
- [ ] update list (contact in case we find error)

D: 
- [x] create dataset
- [ ] make list of used files/sources

H:
- [x] add NORMAL
- [x] add OTHER
- [x] randomize split
- [x] train model on new dataset
- [x] update methodology for new model (spliting patients etc)
- [x] upload model to server & ping A once it's online
- [ ] add installation instructions in readme.md, including:
- [x] how to install dependencies
   - [x] fastai2
   - [x] jupyter notebook
   - [ ] optional: how to set up a venv?
- [ ] how to get the data
- [ ] our testing/training setup
- [ ] link to jupyter notebook which shows
   - [ ] how to train
   - [ ] screenshots of results
- [ ] link to "how to sign up on kaggle"
- [ ] how to export model
- [ ] how to do inference
- [ ] create instruction set for what to update when we get new data
- [x] calculate statistical metrics
    - [x] accuracy
    - [x] sensitivity
    - [x] precision
- [ ] add command line arguments to inference.py so that users can call the script with a file directly
- [ ] add file with URLs to dataset to repo
